# Generated by Django 4.0.2 on 2022-03-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_admin_owner_personal_info_saved_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
