# Generated by Django 4.0.2 on 2022-05-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['name'], 'verbose_name': 'Ahmed'},
        ),
    ]
