# Generated by Django 4.0.2 on 2022-05-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_alter_house_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['name'], 'verbose_name': 'House'},
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
