# Generated by Django 4.0.2 on 2022-05-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_alter_house_options_house_price_alter_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
