# Generated by Django 4.0.2 on 2022-05-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_house_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
