# Generated by Django 4.0.2 on 2022-05-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_house_created_house_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
