# Generated by Django 4.0.2 on 2022-05-11 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0006_alter_house_created_alter_house_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
