# Generated by Django 4.0.2 on 2022-05-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0007_alter_house_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='date',
        ),
        migrations.RemoveField(
            model_name='house',
            name='time',
        ),
    ]
