# Generated by Django 4.0.2 on 2022-05-12 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flats', '0010_remove_personal_info_info_personal_info_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='Property',
        ),
        migrations.CreateModel(
            name='property_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.property')),
            ],
        ),
    ]
