# Generated by Django 4.0.2 on 2022-05-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0012_login_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='h',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
