# Generated by Django 4.0.2 on 2022-06-01 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_city_alter_property_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property_type'),
        ),
        migrations.AlterField(
            model_name='property_type',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
