# Generated by Django 4.0.2 on 2022-06-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_type_user'),
        ('properties', '0004_remove_property_user_property_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedProb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='new_photos/%y/%m/%d')),
                ('videos', models.FileField(null=True, upload_to='videos/%y/%m/%d')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('location', models.URLField()),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property_type')),
            ],
        ),
    ]
