# Generated by Django 4.0.2 on 2022-06-03 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_uploadedprob'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedprob',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
