# Generated by Django 4.0.2 on 2022-05-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='new-user', max_length=100, null=True)),
                ('last_name', models.CharField(default='new-user', max_length=100, null=True)),
                ('username', models.CharField(default='new-user', max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('confirm_password', models.CharField(default='new-user', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'new-users',
            },
        ),
    ]
