# Generated by Django 4.0.2 on 2022-06-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_roles_role_roles_role_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='role',
            new_name='user',
        ),
    ]
