# Generated by Django 4.0.2 on 2022-05-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='Hi', upload_to='photos/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=3, default='Hi', max_digits=6)),
                ('condition', models.TextField(default='start type the condition of the House ')),
                ('view', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='Hi', upload_to='photos/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=3, default='Hi', max_digits=6)),
                ('condition', models.TextField(default='start type the condition of the House ')),
                ('view', models.TextField(default='Hi')),
            ],
        ),
    ]
